### PR TITLE
Removes wrapping from FSN logo

### PR DESCRIPTION
**Pull request by eluciano11**
# What changed and why

@froi reported an issue (#25) last week and it seems like the FSN logo gets broken on iPads. To fix this I removed the flexbox wrapping on the logo and I made the navbar scrollable on the x-axis.

@froi I'm not sure if this solves the issue because I don't have an iPad to test the branch so it would be good if you could give me some feedback before merging. Netlify generates a deploy preview that you'll be able to access on your device.

### CODE REVIEW

**Comment by froi** [comment]
Gracias @eluciano11. Le doy un vistazo.

**Comment by froi** [comment]
Same issue as before;
FireFox

image

Chrome:

image

Usando las herramientas de Chrome o Firefox no presentan este problema.

**Comment by froi** [comment]
Mobile debugging on Safari shows this:

image

I've also viewed the site on a iPhone 11 Pro Max and have the same issue on all browsers.

----

Here's Safari, Firefox, and Chrome side by side. The same issue pops up in Safari on my Mac.

image

Safari on desktop is showing this issue. I don't know enough of frontend magic to begin to guess why this is and why it affects all browsers in iOS and IPadOS.
----

If you all want to push this forward and deploy into "prod" and ask for community assistance then I'm 100% onboard with your decision. Even though I don't like it, itt doesn't break the site functionality to the point that it's unusable.

Thoughts?

**Comment by eluciano11** [comment]
oh... I just saw it on Safari. Fixing...

**Comment by eluciano11** [comment]
@froi I think it should be fixed now. The issue definitely was the text that was being shown to the right of the FSN logo. I remember I changed that from an SVG to an SVG and text and now I nuked it to be a good old png instead. :)

I checked the site in Chrome, Mozilla and Safari. It should be fixed now. Could you please confirm that it's working on your end as well?

**Comment by eluciano11** [comment]
Awesome! Thanks for pointing this out. I didn't do any testing in Safari so you helped us dodge a bullet! :D

**Pull request merged**
